### ISSUE TITLE
KeyError: 'EBOOK_ENG_REGULAR_FONT

### ISSUE THREAD

**Issue by TheKiteRunning** [lepture/getbook#1]
Hi, thank you for your package, I have searched it for so long!

While parsing some urls via feed or json, the error happens：**KeyError: 'EBOOK_ENG_REGULAR_FONT**

Win10 X64, python 3.6,  getbook V0.2

Below lists some of the urls:
- https://feeds.appinn.com/appinns/
- https://www.laohuang.net/feed/

```
PS E:\getbook-0.2> getbook -u https://feeds.appinn.com/appinns/
From network: 检查网页中可能违反「新广告法」的描述，支持 OCR [Chrome]
From network: Snapmod – 漂亮的带壳截图，支持 Pixel、Galaxy、Mi、Meizu、iPhone 主流手机外壳
From network: 让你的手机像 Google Pixel 3 一样[Android]
From network: 一个“反叛”的浏览器扩展 [Chrome/Safari]
From network: 在浮动窗口中打开任何网站，并置顶显示 [Windows/macOS/Linux]
From network: 随机事件生成器：骰子、扑克牌、硬币正反面、数字[Android]
From network: 用手机做监控摄像头，实时保存录像至 NAS 中储存
From network: 超简单摄影黄金和蓝色时间计算器 [Android]
From network: 用计算器做成游戏，你”玩过”计算器吗？
From network: Flightradar24 – 用摄像头（AR）对着天空扫飞机，实时查看航班信息[iOS/Android]
Traceback (most recent call last):
  File "D:\InstallFolder\Anaconda\Scripts\getbook-script.py", line 11, in <module>
    load_entry_point('getbook==0.2', 'console_scripts', 'getbook')()
  File "D:\InstallFolder\Anaconda\lib\site-packages\getbook-0.2-py3.6.egg\getbook\cli.py", line 140, in main
    bg.build(book, force=args.force, epub=args.epub, mobi=args.mobi)
  File "D:\InstallFolder\Anaconda\lib\site-packages\getbook-0.2-py3.6.egg\getbook\gen.py", line 52, in build
    builder.build(output, epub=epub, mobi=mobi)
  File "D:\InstallFolder\Anaconda\lib\site-packages\getbook-0.2-py3.6.egg\getbook\ebook\builder.py", line 155, in build
    self.write_cover(book)
  File "D:\InstallFolder\Anaconda\lib\site-packages\getbook-0.2-py3.6.egg\getbook\ebook\builder.py", line 106, in write_cover
    if self._cover and _create_cover(self._cover['src']):
  File "D:\InstallFolder\Anaconda\lib\site-packages\getbook-0.2-py3.6.egg\getbook\ebook\builder.py", line 96, in _create_cover
    cover = create_book_cover(self.config, book, src, image_dir)
  File "D:\InstallFolder\Anaconda\lib\site-packages\getbook-0.2-py3.6.egg\getbook\ebook\processor.py", line 140, in create_book_cover
    cover.draw_top_text(pubdate)
  File "D:\InstallFolder\Anaconda\lib\site-packages\getbook-0.2-py3.6.egg\getbook\ebook\cover.py", line 44, in draw_top_text
    font_file = self.config['EBOOK_ENG_REGULAR_FONT']
KeyError: 'EBOOK_ENG_REGULAR_FONT'
```

Also some from https://www.cnblogs.com/configure/p/3953394.html even return no contents:
```
getbook -u http://songshuhui.net/feed
Error: RuntimeError('No content',)
```

**Comment by lepture** [comment]
wow, it can actually run on windows. I haven't tested it on windows.

It is caused by generating the "cover" of the book. The building of the cover requires some fonts, which can be loaded with configuration. Checkout the code here: https://github.com/lepture/getbook/blob/master/getbook/cli.py#L25

You're welcome to submit a PR.

**Comment by TheKiteRunning** [comment]
Yes, it works, and let me try how to modify it, though I have little experience on this. Thank you for your help. By the way, I just find I have followed you on twitter, lol
